### ISSUE TITLE
Error when switching off animations

### ISSUE THREAD

**Issue by Mediazept** [yfridelance/contao-accessible_tabs#2]
If I switch off tab animations (setting "Animation" to "-"), tab switching doesn't work. Clicking on a tab link sets all tab contents to "invisible". 
I get a JS error [line 147]:

``` javascript
TypeError: $(...).find(...).eq(...)[o.options.fx] is not a function
$(el).find(o.options.tabbody).eq(i)[o.options.fx](o.options.fxspeed);
```

If I set any type of animation, the script works as expected. Clearing the field for animation duration doesn't improve.
Tested with Contao 3.1.1 and jQuery
See also https://community.contao.org/de/showthread.php?33614-Accessible-Tabs&p=275055&viewfull=1#post275055

**Comment by yfridelance** [comment]
Fixed
