### ISSUE TITLE
Bug & FR aus Forum

### ISSUE THREAD

**Issue by zonky2** [yfridelance/contao-accessible_tabs#6]
siehe https://community.contao.org/de/showthread.php?33614-Accessible-Tabs&p=323526&viewfull=1#post323526

Gruss

**Comment by yfridelance** [comment]
Der Hashtag wird von Google nicht indexiert. Aus diesem Grund sehe ich keinen Handlungsbedarf. Das Updatescript werd ich nochmals prüfen
